CREATE TABLE IF NOT EXISTS todos (
		id SERIAL PRIMARY KEY,
		uuid uuid NOT NULL DEFAULT (gen_random_uuid()),
		title TEXT NOT NULL,
		created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
		updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);